apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: docket-api
    app.kubernetes.io/part-of: open-case-filing-system
    app.kubernetes.io/component: api
  name: docket-api-sa