apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: docket-api
    app.kubernetes.io/part-of: open-case-filing-system
    app.kubernetes.io/component: api
  name: docket-api-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: docket-api