apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: docket-api
    app.kubernetes.io/part-of: open-case-filing-system
    app.kubernetes.io/component: api
  name: docket-api-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  # - name: https
  #   protocol: TCP
  #   port: 443
  #   targetPort: 3000
  selector:
    app.kubernetes.io/name: docket-api
  type: ClusterIP
status:
  loadBalancer: {}