[workspace]
members =  [
    "docket-api",
    "web",
    "common"
]
resolver = "2"


[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
