apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        team: "fcsf"
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/federal-courts-software-factory/open-case-filing-system/web:main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 3000
              protocol: TCP
         