apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: open-case-filing-system
    app.kubernetes.io/component: api
  name: web-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  # - name: https
  #   protocol: TCP
  #   port: 443
  #   targetPort: 3000
  selector:
    app.kubernetes.io/name: web