apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-test
  name: web-test
  namespace: dev
spec:
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - image: ghcr.io/federal-courts-software-factory/open-case-filing-system/web:sha-024ece0
        name: web-test
        env:
        - name: POSTGRES_DB
          value: "postgres"

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app.kubernetes.io/name: web
#     app.kubernetes.io/part-of: open-case-filing-system
#     app.kubernetes.io/component: api
#   name: web
#   namespace: dev 
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: web
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: web
#     spec:
#       serviceAccountName: web-sa
#       containers:
#         - name: web
#           image: ghcr.io/federal-courts-software-factory/open-case-filing-system/web:sha-946daa7
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 3000
#           resources:
#             requests:
#               cpu: 200m
#               memory: 256Mi
#             limits:
#               cpu: 500m
#               memory: 1Gi

