---
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: simple
  namespace: surrealdb-demo
spec:
  version: v6.5.0
  timezone: UTC
  configUpdateStrategy: RollingUpdate
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  schedulerName: default-scheduler
  # Disable for demo purpose
  # topologySpreadConstraints:
  #   - topologyKey: topology.kubernetes.io/zone
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 3
    storageClassName: pd-custom
    requests:
      storage: "10Gi"
    config: |
      [dashboard]
        internal-proxy = true
      [replication]
        location-labels = ["topology.kubernetes.io/zone", "kubernetes.io/hostname"]
        max-replicas = 3
    # nodeSelector:
    #   dedicated: pd
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: pd
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - pd
            topologyKey: kubernetes.io/hostname
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 3
    storageClassName: pd-custom
    requests:
      storage: "10Gi" # Adjust as necessary
    annotations:
      tidb.pingcap.com/sysctl-init: "true"
    podSecurityContext:
      sysctls:
        - name: net.core.somaxconn
          value: "32768"
    config: {}
    # nodeSelector:
    #   dedicated: tikv
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tikv
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - tikv
            topologyKey: kubernetes.io/hostname
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 0
    service: {}
