name: Build Release

on: push
    
jobs:
  build:
    name: Repro compilation bug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install musl-tools
        run: |
          sudo apt-get update -y
          sudo apt-get install musl-tools -y

      - name: Install rust
        run: |
          rustup target add x86_64-unknown-linux-musl 

      - name: Build
        run: cargo build --verbose --target x86_64-unknown-linux-musl